
-- Drop tables antigas se existirem para evitar conflitos
DROP TABLE IF EXISTS artigos_excecoes CASCADE;
DROP TABLE IF EXISTS artigos_inelegiveis CASCADE;
DROP TABLE IF EXISTS normas CASCADE;
DROP TABLE IF EXISTS crimes_inelegibilidade CASCADE;

-- Drop function antiga
DROP FUNCTION IF EXISTS public.verificar_elegibilidade(text, text, text, text, text);
DROP FUNCTION IF EXISTS public.verificar_elegibilidade(character varying, character varying, character varying, character varying, character varying);

-- Nova Tabela Unificada
CREATE TABLE IF NOT EXISTS crimes_inelegibilidade (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL, -- Código para API (ex: CP, CE)
    lei VARCHAR(100) NOT NULL,   -- Nome descritivo (ex: Código Penal)
    artigo VARCHAR(50) NOT NULL,
    paragrafo VARCHAR(50),
    inciso VARCHAR(50),
    alinea VARCHAR(50),
    combinacao VARCHAR(100),
    eh_excecao BOOLEAN DEFAULT FALSE,
    tipo_crime VARCHAR(200),
    item_alinea_e VARCHAR(50),
    observacoes TEXT
);

CREATE INDEX IF NOT EXISTS idx_crimes_codigo ON crimes_inelegibilidade(codigo);
CREATE INDEX IF NOT EXISTS idx_crimes_artigo ON crimes_inelegibilidade(artigo);

-- Script SQL para inserção de crimes que ensejam inelegibilidade
-- Baseado na Tabela Oficial da Corregedoria Regional Eleitoral de São Paulo
-- LC 64/90, atualizada pela LC 135/2010



-- CÓDIGO PENAL (Decreto-Lei 2.848/40)

-- Crimes contra a vida (9)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '121', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '121', '3', NULL, NULL, NULL, TRUE, 'Crimes contra a vida', '9', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '121-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra a vida', '9', 'Exceção - Crime de ação penal privada'),
('CP', 'Código Penal (DL 2.848/40)', '122', '1', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', '2', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', '3', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', '4', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', '5', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', '6', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '122', '7', NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '123', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '124', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '125', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '126', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '127', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', NULL);

-- Crime hediondo (7) - Lesão corporal
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '129', '2', NULL, NULL, '§ 12', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 13.142/2015 e Lei 14.811/2024'),
('CP', 'Código Penal (DL 2.848/40)', '129', '3', NULL, NULL, '§ 12', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 13.142/2015 e Lei 14.811/2024');

-- Crime de redução à condição análoga à de escravo e contra dignidade sexual (8 e 9)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '148', '1', 'IV', NULL, NULL, FALSE, 'Crime de redução à condição análoga à de escravo e contra dignidade sexual', '8 e 9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '149', NULL, NULL, NULL, NULL, FALSE, 'Crime de redução à condição análoga à de escravo e contra dignidade sexual', '8 e 9', NULL);

-- Crime hediondo (7) - Tráfico de pessoas
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '149-A', 'caput', 'I', NULL, '§ 1º, II', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 14.811/2024'),
('CP', 'Código Penal (DL 2.848/40)', '149-A', 'caput', 'II', NULL, '§ 1º, II', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 14.811/2024'),
('CP', 'Código Penal (DL 2.848/40)', '149-A', 'caput', 'III', NULL, '§ 1º, II', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 14.811/2024'),
('CP', 'Código Penal (DL 2.848/40)', '149-A', 'caput', 'IV', NULL, '§ 1º, II', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 14.811/2024'),
('CP', 'Código Penal (DL 2.848/40)', '149-A', 'caput', 'V', NULL, '§ 1º, II', FALSE, 'Crime hediondo', '7', 'Crime definido como hediondo pela Lei 14.811/2024');

-- Crimes contra o patrimônio (1 e 2)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '155', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '157', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '158', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '159', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '160', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '162', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '163', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '163', 'unico', 'IV', NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '163', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '168', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '168-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '171', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '172', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '173', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '174', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '175', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '175', NULL, 'I', NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '175', NULL, 'II', NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '175', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '177', '2', NULL, NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '177', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '178', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '180', '3', NULL, NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '180', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '180-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC'),
('CP', 'Código Penal (DL 2.848/40)', '184', '4', NULL, NULL, NULL, TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '184', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Entendimento firmado pelo TSE no REsp Eleitoral nº 145-94.2016.6.24.0074/SC');

-- Crimes contra a dignidade sexual (9)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '213', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '215', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '216-A', NULL, NULL, NULL, NULL, TRUE, 'Crimes contra a dignidade sexual', '9', 'Exceção'),
('CP', 'Código Penal (DL 2.848/40)', '216-B', NULL, NULL, NULL, NULL, TRUE, 'Crimes contra a dignidade sexual', '9', 'Exceção'),
('CP', 'Código Penal (DL 2.848/40)', '218', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '218-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '218-B', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '218-C', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '221', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '227', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Revogado pela Lei 11.106/2005, Lei 12.015/2009, Lei 13.344/2016'),
('CP', 'Código Penal (DL 2.848/40)', '228', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '229', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '230', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('CP', 'Código Penal (DL 2.848/40)', '231-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Revogado pela Lei 11.106/2005, Lei 12.015/2009, Lei 13.344/2016');

-- Crimes contra a saúde pública (3)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '267', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '267', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '270', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '270', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '271', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '271', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '272', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '272', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '273', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '273', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '274', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '275', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '276', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '277', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '278', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '278', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '280', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a saúde pública', '3', NULL),
('CP', 'Código Penal (DL 2.848/40)', '280', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra a saúde pública', '3', 'Exceção - Crime culposo');

-- Crimes praticados por quadrilha ou bando (10)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '288', NULL, NULL, NULL, NULL, FALSE, 'Crimes praticados por quadrilha ou bando', '10', NULL),
('CP', 'Código Penal (DL 2.848/40)', '288-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes praticados por quadrilha ou bando', '10', NULL);

-- Crimes contra a fé pública (1)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '289', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '289', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a fé pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '290', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '291', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '293', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '293', '4', NULL, NULL, NULL, TRUE, 'Crimes contra a fé pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '294', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '296', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '297', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '298', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '299', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '300', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '303', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '304', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '304', NULL, NULL, NULL, 'arts. 301 e 302', TRUE, 'Crimes contra a fé pública', '1', 'Exceção - Nas figuras dos arts. 301 e 302'),
('CP', 'Código Penal (DL 2.848/40)', '305', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '306', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '309', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '310', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '311', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '311-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL);

-- Crimes contra a administração pública (1)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CP', 'Código Penal (DL 2.848/40)', '312', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '312', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '313', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '313-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '314', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '316', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '317', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '317', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '318', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '322', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '323', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '323', '1', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '323', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '325', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '325', '1', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '325', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '328', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '328', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '332', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '333', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '334', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '334-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '337', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '337-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '337-B', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '337-C', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '338', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '339', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '342', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '343', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '344', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '347', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime de menor potencial ofensivo'),
('CP', 'Código Penal (DL 2.848/40)', '347', 'unico', NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '351', 'caput', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '351', '4', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública', '1', 'Exceção - Crime culposo'),
('CP', 'Código Penal (DL 2.848/40)', '351', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '353', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '355', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '356', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '357', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '359-C', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '359-D', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '359-G', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('CP', 'Código Penal (DL 2.848/40)', '359-H', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL);

-- CÓDIGO PENAL MILITAR (Decreto-Lei nº 1.001/69)

-- Crimes contra a vida (9) - CPM
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '205', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '207', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes hediondos (7) - CPM
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '208', NULL, NULL, NULL, NULL, FALSE, 'Crimes hediondos', '7', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra a dignidade sexual (9) - CPM
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '232', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '233', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '234', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '235', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '238', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '239', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra o patrimônio (1 e 2) - CPM
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '240', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '241', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '242', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '243', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '244', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '245', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '246', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '247', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '248', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '249', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '250', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '251', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '252', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '253', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '254', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '257', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '258', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '259', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '260', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '261', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '262', NULL, NULL, NULL, 'art. 266', TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime culposo quando combinado com art. 266'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '262', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '263', NULL, NULL, NULL, 'art. 266', TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime culposo quando combinado com art. 266'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '263', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '264', NULL, NULL, NULL, 'art. 266', TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime culposo quando combinado com art. 266'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '264', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '265', NULL, NULL, NULL, 'art. 266', TRUE, 'Crimes contra o patrimônio', '1 e 2', 'Exceção - Crime culposo quando combinado com art. 266'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '265', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '267', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra o meio ambiente e a saúde pública (3) - CPM
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '290', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '291', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '292', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '292', '2', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '293', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '293', '3', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '294', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '294', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '295', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '295', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '296', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '296', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '297', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente e a saúde pública', '3', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra a administração pública e a fé pública (1) - CPM
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '298', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '299', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '300', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '301', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '302', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '303', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '303', '3', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública e a fé pública', '1', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '304', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '305', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '306', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '307', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '308', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '309', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '310', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '311', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '312', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '313', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '314', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '315', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '316', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '317', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '318', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '319', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '320', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '321', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '322', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '324', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '325', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '326', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '327', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '328', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '329', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '330', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '331', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '332', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '332', '2', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública e a fé pública', '1', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '333', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '334', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '335', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '336', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '337', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '338', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '339', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '340', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '341', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '342', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '343', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '344', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '345', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '346', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '347', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '348', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '349', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '350', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '351', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '352', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '352', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra a administração pública e a fé pública', '1', 'Exceção - Crime culposo'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '353', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '354', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública e a fé pública', '1', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra a vida (9) - CPM (continuação)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '400', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a vida', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes hediondos (7) - CPM (continuação)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '401', NULL, NULL, NULL, NULL, FALSE, 'Crimes hediondos', '7', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '402', NULL, NULL, NULL, NULL, FALSE, 'Crimes hediondos', '7', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra o patrimônio (1 e 2) - CPM (continuação)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '404', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '405', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '406', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o patrimônio', '1 e 2', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- Crimes contra a dignidade sexual (9) - CPM (continuação)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CPM', 'Código Penal Militar (DL 1.001/69)', '407', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95'),
('CPM', 'Código Penal Militar (DL 1.001/69)', '408', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', 'Conceito de crime de menor potencial ofensivo não se aplica - art. 90-A, Lei 9.099/95');

-- OUTRAS LEIS

-- Decreto-Lei 5.452/43 - CLT
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CLT', 'CLT (DL 5.452/43)', '49', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a fé pública', '1', NULL);

-- Decreto-Lei 7.661/45 - Lei Falimentar (revogada)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('DL_7661_45', 'Decreto-Lei 7.661/45', '186', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', 'Lei revogada pela Lei 11.101/2005'),
('DL_7661_45', 'Decreto-Lei 7.661/45', '187', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', 'Lei revogada pela Lei 11.101/2005'),
('DL_7661_45', 'Decreto-Lei 7.661/45', '188', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', 'Lei revogada pela Lei 11.101/2005'),
('DL_7661_45', 'Decreto-Lei 7.661/45', '189', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', 'Lei revogada pela Lei 11.101/2005');

-- Decreto-Lei 201/67 - Crimes de responsabilidade dos Prefeitos
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('DL_201_67', 'Crimes de Responsabilidade (DL 201/67)', '1º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL);

-- Lei Complementar 105/01
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('LC_105_01', 'Lei Complementar 105/01', '10', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL);

-- Lei 1.521/51
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_1521_51', 'Lei 1.521/51', '3º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', NULL);

-- Lei 2.889/56 - Genocídio
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_2889_56', 'Lei 2.889/56', '1º', NULL, NULL, NULL, NULL, FALSE, 'Crimes hediondos', '7', NULL),
('lei_2889_56', 'Lei 2.889/56', '2º', 'caput', NULL, NULL, NULL, TRUE, 'Crimes hediondos', '7', 'Exceção - Quando se referir ao art. 1º, alínea "e"'),
('lei_2889_56', 'Lei 2.889/56', '2º', NULL, NULL, NULL, NULL, FALSE, 'Crimes hediondos', '7', NULL),
('lei_2889_56', 'Lei 2.889/56', '3º', 'caput', NULL, NULL, NULL, TRUE, 'Crimes hediondos', '7', 'Exceção - Quando se referir ao art. 1º, alínea "e"'),
('lei_2889_56', 'Lei 2.889/56', '3º', NULL, NULL, NULL, NULL, FALSE, 'Crimes hediondos', '7', NULL);

-- Lei 4.591/64
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_4591_64', 'Lei 4.591/64', '65', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', NULL);

-- Lei 4.595/64
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_4595_64', 'Lei 4.595/64', '34', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL);

-- Lei 4.728/65
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_4728_65', 'Lei 4.728/65', '66-B', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o mercado de capitais', '2', NULL),
('lei_4728_65', 'Lei 4.728/65', '73', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o mercado de capitais', '2', NULL),
('lei_4728_65', 'Lei 4.728/65', '74', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o mercado de capitais', '2', NULL);

-- Lei 4.737/65 - Código Eleitoral
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('CE', 'Código Eleitoral (Lei 4.737/65)', '289', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '291', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '298', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '299', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '301', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '302', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '307', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '308', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '309', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '315', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '316', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '317', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '339', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '340', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '348', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '349', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '350', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '352', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '353', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '354', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('CE', 'Código Eleitoral (Lei 4.737/65)', '354-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL);

-- Lei 4.898/65
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_4898_65', 'Lei 4.898/65', '6º', '3', NULL, 'c', NULL, FALSE, 'Crimes de abuso de autoridade', '5', NULL);

-- Lei 6.091/74
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_6091_74', 'Lei 6.091/74', '11', NULL, 'III', NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('lei_6091_74', 'Lei 6.091/74', '11', NULL, 'IV', NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL);

-- Lei 6.368/76 - Lei de Drogas (revogada)
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_6368_76', 'Lei 6.368/76', '12', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', 'Lei revogada pela Lei 11.343/2006'),
('lei_6368_76', 'Lei 6.368/76', '13', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', 'Lei revogada pela Lei 11.343/2006'),
('lei_6368_76', 'Lei 6.368/76', '14', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', 'Lei revogada pela Lei 11.343/2006');

-- Lei 6.385/76
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_6385_76', 'Lei 6.385/76', '27-C', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o mercado de capitais', '2', NULL),
('lei_6385_76', 'Lei 6.385/76', '27-D', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o mercado de capitais', '2', NULL);

-- Lei 6.766/79
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_6766_79', 'Lei 6.766/79', '50', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('lei_6766_79', 'Lei 6.766/79', '51', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL);

-- Lei 6.996/82
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_6996_82', 'Lei 6.996/82', '15', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL);

-- Lei 7.492/86 - Lei do Colarinho Branco
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_7492_86', 'Lei 7.492/86', '2º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '3º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '4º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '5º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '6º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '7º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '8º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '9º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '10', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '11', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '12', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '13', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '14', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '15', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '16', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '17', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '18', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '19', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '20', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '21', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '22', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL),
('lei_7492_86', 'Lei 7.492/86', '23', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o sistema financeiro', '2', NULL);

-- Lei 7.716/89 - Crimes de racismo
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_7716_89', 'Lei 7.716/89', '2º-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '3º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '4º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '5º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '6º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '7º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '8º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '9º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '10', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '11', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '12', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '13', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '14', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL),
('lei_7716_89', 'Lei 7.716/89', '20', NULL, NULL, NULL, NULL, FALSE, 'Crimes de racismo', '7', NULL);

-- Lei 8.069/90 - ECA
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('ECA', 'Estatuto da Criança (ECA)', '240', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('ECA', 'Estatuto da Criança (ECA)', '241', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('ECA', 'Estatuto da Criança (ECA)', '241-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('ECA', 'Estatuto da Criança (ECA)', '241-B', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('ECA', 'Estatuto da Criança (ECA)', '241-C', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('ECA', 'Estatuto da Criança (ECA)', '241-D', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL),
('ECA', 'Estatuto da Criança (ECA)', '244-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a dignidade sexual', '9', NULL);

-- Lei 8.137/90
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_8137_90', 'Lei 8.137/90', '1º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', NULL),
('lei_8137_90', 'Lei 8.137/90', '3º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', NULL),
('lei_8137_90', 'Lei 8.137/90', '4º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', NULL),
('lei_8137_90', 'Lei 8.137/90', '5º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', 'Revogado pela Lei 12.529/2011'),
('lei_8137_90', 'Lei 8.137/90', '6º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', 'Revogado pela Lei 12.529/2011'),
('lei_8137_90', 'Lei 8.137/90', '7º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular', '1', NULL),
('lei_8137_90', 'Lei 8.137/90', '7º', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra a economia popular', '1', 'Exceção');

-- Lei 8.176/91
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_8176_91', 'Lei 8.176/91', '1º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular e contra o patrimônio', '1', NULL),
('lei_8176_91', 'Lei 8.176/91', '2º', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a economia popular e contra o patrimônio', '1', NULL);

-- Lei 8.666/93
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_8666_93', 'Lei 8.666/93', '89', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('lei_8666_93', 'Lei 8.666/93', '90', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('lei_8666_93', 'Lei 8.666/93', '92', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('lei_8666_93', 'Lei 8.666/93', '94', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('lei_8666_93', 'Lei 8.666/93', '95', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL),
('lei_8666_93', 'Lei 8.666/93', '96', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra a administração pública', '1', NULL);

-- Lei 9.455/97 - Tortura
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_9455_97', 'Lei 9.455/97', '1º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tortura', '7', NULL);

-- Lei 9.504/97
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_9504_97', 'Lei das Eleições (9.504/97)', '57-H', '1', NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL),
('lei_9504_97', 'Lei das Eleições (9.504/97)', '72', NULL, NULL, NULL, NULL, FALSE, 'Crimes eleitorais', '4', NULL);

-- Lei 9.605/98 - Lei Ambiental
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_9605_98', 'Lei 9.605/98', '30', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '33', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '34', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '35', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '38', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '38', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '38-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '38-A', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '39', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '40', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '40', '3', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '41', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '41', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '42', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '50-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '54', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '54', '1', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '56', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '56', '3', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '61', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '62', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '62', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '63', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '66', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '67', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '67', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '68', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '68', 'unico', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo'),
('lei_9605_98', 'Lei 9.605/98', '69', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '69-A', NULL, NULL, NULL, NULL, FALSE, 'Crimes contra o meio ambiente', '3', NULL),
('lei_9605_98', 'Lei 9.605/98', '69-A', '1', NULL, NULL, NULL, TRUE, 'Crimes contra o meio ambiente', '3', 'Exceção - Crime culposo');

-- Lei 9.613/98 - Lavagem de dinheiro
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_9613_98', 'Lei 9.613/98', '1º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de lavagem ou ocultação de bens, direitos e valores', '6', NULL);

-- Lei 10.826/03 - Armas de Fogo
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_10826_03', 'Estatuto do Desarmamento', '16', 'caput', NULL, NULL, '2', FALSE, 'Crime hediondo', '7', 'Alterações promovidas pela Lei 13.964/2019'),
('lei_10826_03', 'Estatuto do Desarmamento', '16', '1', NULL, NULL, '2', FALSE, 'Crime hediondo', '7', 'Alterações promovidas pela Lei 13.964/2019'),
('lei_10826_03', 'Estatuto do Desarmamento', '17', NULL, NULL, NULL, NULL, FALSE, 'Crime hediondo', '7', 'Alterações promovidas pela Lei 13.964/2019'),
('lei_10826_03', 'Estatuto do Desarmamento', '18', NULL, NULL, NULL, NULL, FALSE, 'Crime hediondo', '7', 'Alterações promovidas pela Lei 13.964/2019');

-- Lei 11.101/05 - Lei Falimentar
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_11101_05', 'Lei de Falências (11.101/05)', '168', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '169', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '170', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '171', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '172', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '173', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '174', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '175', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '176', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL),
('lei_11101_05', 'Lei de Falências (11.101/05)', '177', NULL, NULL, NULL, NULL, FALSE, 'Crimes previstos na lei que regula a falência', '2', NULL);

-- Lei 11.343/06 - Lei de Drogas
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_11343_06', 'Lei de Drogas (11.343/06)', '33', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', NULL),
('lei_11343_06', 'Lei de Drogas (11.343/06)', '33', '3', NULL, NULL, NULL, TRUE, 'Crimes de tráfico de entorpecentes', '7', 'Exceção'),
('lei_11343_06', 'Lei de Drogas (11.343/06)', '34', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', NULL),
('lei_11343_06', 'Lei de Drogas (11.343/06)', '35', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', NULL),
('lei_11343_06', 'Lei de Drogas (11.343/06)', '36', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', NULL),
('lei_11343_06', 'Lei de Drogas (11.343/06)', '37', NULL, NULL, NULL, NULL, FALSE, 'Crimes de tráfico de entorpecentes', '7', NULL);

-- Lei 12.850/13 - Organização Criminosa
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_12850_13', 'Lei 12.850/13', '2º', NULL, NULL, NULL, NULL, FALSE, 'Crimes Praticados por Organização Criminosa', '10', 'Art. 2º define o crime de promover, constituir, financiar ou integrar organização criminosa');

-- Lei 13.260/16 - Terrorismo
INSERT INTO crimes_inelegibilidade (codigo, lei, artigo, paragrafo, inciso, alinea, combinacao, eh_excecao, tipo_crime, item_alinea_e, observacoes) VALUES
('lei_13260_16', 'Lei 13.260/16', '2º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de terrorismo', NULL, NULL),
('lei_13260_16', 'Lei 13.260/16', '3º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de terrorismo', NULL, NULL),
('lei_13260_16', 'Lei 13.260/16', '4º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de terrorismo', NULL, NULL),
('lei_13260_16', 'Lei 13.260/16', '5º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de terrorismo', NULL, NULL),
('lei_13260_16', 'Lei 13.260/16', '6º', NULL, NULL, NULL, NULL, FALSE, 'Crimes de terrorismo', NULL, NULL);

-- Fim do script


-- Drop function antiga ANTES de recriar (evita erro de mudança de retorno)
DROP FUNCTION IF EXISTS public.verificar_elegibilidade(text, text, text, text, text);

-- Nova Função RPC otimizada com metadados de exceção para UI V3
-- Nova Função RPC corrigida (resolvendo ambiguidade de colunas)
CREATE OR REPLACE FUNCTION public.verificar_elegibilidade(
    p_codigo_norma TEXT,
    p_artigo TEXT,
    p_paragrafo TEXT DEFAULT NULL,
    p_inciso TEXT DEFAULT NULL,
    p_alinea TEXT DEFAULT NULL
)
RETURNS TABLE (
    resultado VARCHAR,
    tipo_crime TEXT,
    observacoes TEXT,
    motivo TEXT,
    item_alinea_e VARCHAR,
    excecoes_detalhes TEXT
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_record record;
    v_excecoes_list TEXT;
BEGIN
    -- 1. Buscar o registro mais específico (usando alias 't' para evitar conflito com parâmetros de retorno)
    -- REGRA: se usuário não especificou parágrafo, buscar o CAPUT (não qualquer parágrafo)
    -- Isso segue a tabela oficial onde "Art. X" sem especificação = caput
    SELECT 
        t.eh_excecao, t.tipo_crime, t.observacoes, t.item_alinea_e
    INTO v_record
    FROM public.crimes_inelegibilidade t
    WHERE t.codigo = p_codigo_norma 
      AND t.artigo = p_artigo
      AND (
          -- Se parágrafo especificado: buscar exatamente esse parágrafo
          (p_paragrafo IS NOT NULL AND t.paragrafo = p_paragrafo)
          OR
          -- Se parágrafo NÃO especificado: buscar o caput (paragrafo NULL ou 'caput')
          (p_paragrafo IS NULL AND (t.paragrafo IS NULL OR LOWER(t.paragrafo) = 'caput'))
      )
      AND (p_inciso IS NULL OR t.inciso = p_inciso)
      AND (p_alinea IS NULL OR t.alinea = p_alinea)
    ORDER BY 
      (t.paragrafo IS NOT DISTINCT FROM p_paragrafo) DESC,
      (t.inciso IS NOT DISTINCT FROM p_inciso) DESC,
      (t.alinea IS NOT DISTINCT FROM p_alinea) DESC,
      t.eh_excecao ASC 
    LIMIT 1;

    -- 2. Buscar TODAS as exceções para este artigo (Coluna central no UI V3)
    SELECT string_agg(
        CASE 
            WHEN t2.paragrafo IS NOT NULL THEN 'Parágrafo ' || t2.paragrafo 
            WHEN t2.inciso IS NOT NULL THEN 'Inciso ' || t2.inciso 
            WHEN t2.alinea IS NOT NULL THEN 'Alínea ' || t2.alinea 
            ELSE 'Artigo/Caput'
        END || COALESCE(' (' || t2.observacoes || ')', ''), 
        '; '
    ) INTO v_excecoes_list
    FROM public.crimes_inelegibilidade t2
    WHERE t2.codigo = p_codigo_norma 
      AND t2.artigo = p_artigo 
      AND t2.eh_excecao = TRUE;

    IF v_record IS NULL THEN
        RETURN QUERY SELECT 
            'NAO_CONSTA'::VARCHAR, 
            NULL::TEXT, 
            NULL::TEXT, 
            'Artigo não mapeado como impeditivo.'::TEXT,
            NULL::VARCHAR,
            NULL::TEXT;
        RETURN;
    END IF;

    -- 3. Retornar os dados estruturados para o Modal V3
    RETURN QUERY 
    SELECT 
      (CASE WHEN v_record.eh_excecao THEN 'ELEGIVEL' ELSE 'INELEGIVEL' END)::VARCHAR, 
      v_record.tipo_crime::TEXT, 
      v_record.observacoes::TEXT, 
      ('Artigo consta na tabela de inelegibilidade (Item ' || COALESCE(v_record.item_alinea_e, '?') || ')')::TEXT,
      v_record.item_alinea_e::VARCHAR,
      v_excecoes_list::TEXT;
END;
$$;

-- Permissões
GRANT ALL ON TABLE crimes_inelegibilidade TO postgres, service_role;
GRANT SELECT ON TABLE crimes_inelegibilidade TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verificar_elegibilidade(text, text, text, text, text) TO anon, authenticated, service_role;
